# Generated by Django 5.2.16 on 2026-07-30 14:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='Acolhimento', max_length=80)),
                ('mensagem', models.TextField()),
                ('contato_seguro', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tratado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('identifier', models.CharField(max_length=150, unique=True, verbose_name='CPF ou e-mail')),
                ('nome', models.CharField(max_length=150)),
                ('perfil_acesso', models.CharField(choices=[('aluno', 'Aluno'), ('corporativo', 'Corporativo'), ('admin', 'Administrador')], default='aluno', max_length=16)),
                ('area_interesse', models.CharField(blank=True, default='Tecnologia da Informação', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('area', models.CharField(choices=[('Tecnologia da Informação', 'Tecnologia da Informação'), ('Psicologia', 'Psicologia'), ('Saúde', 'Saúde'), ('Engenharia', 'Engenharia'), ('Educação', 'Educação'), ('Arte', 'Arte'), ('Ciência', 'Ciência'), ('Empreendedorismo', 'Empreendedorismo'), ('Educação Física', 'Educação Física'), ('Nutrição', 'Nutrição'), ('Medicina Veterinária', 'Medicina Veterinária'), ('Inglês', 'Inglês')], max_length=100)),
                ('resumo', models.TextField()),
                ('status', models.CharField(choices=[('ideia', 'Ideia'), ('desenvolvimento', 'Em desenvolvimento'), ('concluido', 'Concluído')], default='ideia', max_length=20)),
                ('publico', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='core.studentproject')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('area', models.CharField(choices=[('Tecnologia da Informação', 'Tecnologia da Informação'), ('Psicologia', 'Psicologia'), ('Saúde', 'Saúde'), ('Engenharia', 'Engenharia'), ('Educação', 'Educação'), ('Arte', 'Arte'), ('Ciência', 'Ciência'), ('Empreendedorismo', 'Empreendedorismo'), ('Educação Física', 'Educação Física'), ('Nutrição', 'Nutrição'), ('Medicina Veterinária', 'Medicina Veterinária'), ('Inglês', 'Inglês')], max_length=100)),
                ('data', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('vagas', models.PositiveIntegerField(default=30)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficinas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('presente', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'data')},
            },
        ),
    ]
