# Generated by Django 5.2.16 on 2026-08-18 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque na Vitrine'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='link_github',
            field=models.URLField(blank=True, default='', verbose_name='Repositório / Documentação'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='link_projeto',
            field=models.URLField(blank=True, default='', verbose_name='Link do Protótipo'),
        ),
        migrations.CreateModel(
            name='WorkshopEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_oficinas', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.workshop')),
            ],
            options={
                'unique_together': {('user', 'workshop')},
            },
        ),
    ]
