# Generated by Django 5.2.17 on 2026-08-31 22:46

import base64
import hashlib

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_enterprise_data(apps, schema_editor):
    User = apps.get_model("core", "User")
    SafeReport = apps.get_model("core", "SafeReport")
    User.objects.filter(perfil_acesso="aluno").update(perfil_acesso="student")
    User.objects.filter(perfil_acesso="corporativo").update(perfil_acesso="recruiter")

    from cryptography.fernet import Fernet
    configured = getattr(settings, "SAFE_REPORT_ENCRYPTION_KEY", "")
    key = configured.encode() if configured else base64.urlsafe_b64encode(hashlib.sha256(settings.SECRET_KEY.encode()).digest())
    cipher = Fernet(key)
    for report in SafeReport.objects.all():
        changed = []
        if report.mensagem and not report.mensagem.startswith("enc:v1:"):
            report.mensagem = "enc:v1:" + cipher.encrypt(report.mensagem.encode()).decode()
            changed.append("mensagem")
        if report.contato_seguro and not report.contato_seguro.startswith("enc:v1:"):
            report.contato_seguro = "enc:v1:" + cipher.encrypt(report.contato_seguro.encode()).decode()
            changed.append("contato_seguro")
        if changed:
            report.save(update_fields=changed)


def reverse_enterprise_data(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(perfil_acesso="student").update(perfil_acesso="aluno")
    User.objects.filter(perfil_acesso="recruiter").update(perfil_acesso="corporativo")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentproject_destaque_studentproject_link_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frequencias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safereport',
            name='protocolo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='safereport',
            name='status',
            field=models.CharField(choices=[('open', 'Recebido'), ('in_progress', 'Em acolhimento'), ('resolved', 'Resolvido')], default='open', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='competencias',
            field=models.CharField(blank=True, help_text='Competências separadas por vírgula', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='consentimento_vitrine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='imagem_query',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='safereport',
            name='contato_seguro',
            field=models.TextField(blank=True, help_text='Conteúdo cifrado em repouso'),
        ),
        migrations.AlterField(
            model_name='safereport',
            name='mensagem',
            field=models.TextField(help_text='Conteúdo cifrado em repouso'),
        ),
        migrations.RunPython(migrate_enterprise_data, reverse_enterprise_data),
        migrations.AlterField(
            model_name='user',
            name='perfil_acesso',
            field=models.CharField(choices=[('student', 'Aluno'), ('teacher', 'Professor / Colaborador'), ('admin', 'Administrador'), ('recruiter', 'Recrutador / Empresa')], default='student', max_length=16),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=80)),
                ('entidade', models.CharField(max_length=80)),
                ('entidade_id', models.CharField(blank=True, max_length=64)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Conversa com Tutor PIEM', max_length=120)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Tutor')], max_length=12)),
                ('content', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=24)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.chatsession')),
            ],
            options={
                'ordering': ('criada_em',),
            },
        ),
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('empresa', models.CharField(max_length=160)),
                ('descricao', models.TextField()),
                ('competencias', models.CharField(blank=True, max_length=500)),
                ('modalidade', models.CharField(default='Presencial', max_length=20)),
                ('tipo', models.CharField(choices=[('apprentice', 'Jovem Aprendiz'), ('internship', 'Estágio'), ('entry', 'Primeiro emprego')], default='apprentice', max_length=16)),
                ('localidade', models.CharField(blank=True, max_length=140)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('encerra_em', models.DateTimeField(blank=True, null=True)),
                ('publicada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vagas_publicadas', to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='core.school')),
            ],
            options={
                'ordering': ('-criada_em',),
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('inicio', models.DateTimeField()),
                ('duracao_minutos', models.PositiveSmallIntegerField(default=45)),
                ('link_reuniao', models.URLField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentorias_conduzidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('inicio',),
            },
        ),
        migrations.AddField(
            model_name='safereport',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatos', to='core.school'),
        ),
        migrations.AddField(
            model_name='user',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.school'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oficinas', to='core.school'),
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ano_letivo', models.PositiveIntegerField(default=2026)),
                ('serie', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.school')),
                ('professores', models.ManyToManyField(blank=True, related_name='turmas_docentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-ano_letivo', 'nome'),
                'unique_together': {('escola', 'nome', 'ano_letivo')},
            },
        ),
        migrations.CreateModel(
            name='PracticalChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField()),
                ('area', models.CharField(choices=[('Tecnologia da Informação', 'Tecnologia da Informação'), ('Psicologia', 'Psicologia'), ('Saúde', 'Saúde'), ('Engenharia', 'Engenharia'), ('Educação', 'Educação'), ('Arte', 'Arte'), ('Ciência', 'Ciência'), ('Empreendedorismo', 'Empreendedorismo'), ('Educação Física', 'Educação Física'), ('Nutrição', 'Nutrição'), ('Medicina Veterinária', 'Medicina Veterinária'), ('Inglês', 'Inglês')], max_length=100)),
                ('pontos', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(350)])),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desafios_criados', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='core.schoolclass')),
            ],
            options={
                'ordering': ('prazo', '-criado_em'),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='core.schoolclass'),
        ),
        migrations.CreateModel(
            name='SoftSkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunicacao', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('proatividade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('trabalho_equipe', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_soft_skills', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soft_skills_avaliadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('applied', 'Candidatura enviada'), ('screening', 'Triagem'), ('interview', 'Entrevista'), ('offer', 'Proposta'), ('hired', 'Contratado'), ('rejected', 'Encerrado')], default='applied', max_length=16)),
                ('carta_apresentacao', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='core.jobopportunity')),
            ],
            options={
                'ordering': ('-atualizada_em',),
                'unique_together': {('vaga', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('anexo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Aguardando correção'), ('revision', 'Revisão solicitada'), ('approved', 'Aprovado')], default='pending', max_length=16)),
                ('pontos_atribuidos', models.PositiveSmallIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliado_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_desafios', to=settings.AUTH_USER_MODEL)),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_avaliadas', to=settings.AUTH_USER_MODEL)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.practicalchallenge')),
            ],
            options={
                'ordering': ('-enviado_em',),
                'unique_together': {('desafio', 'aluno')},
            },
        ),
    ]
