# Generated by Django 5.2.17 on 2026-09-01 00:01

import django.core.validators
from django.db import migrations, models


def populate_contact_email(apps, schema_editor):
    User = apps.get_model("core", "User")
    accounts = list(User.objects.filter(identifier__contains="@", email=""))
    for account in accounts:
        account.email = account.identifier.strip().lower()
    if accounts:
        User.objects.bulk_update(accounts, ["email"])


def clear_migrated_contact_email(apps, schema_editor):
    User = apps.get_model("core", "User")
    for account in User.objects.filter(identifier__contains="@").iterator():
        if account.email == account.identifier.strip().lower():
            account.email = ""
            account.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_school_attendance_registrado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ('data', 'titulo')},
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail de contato'),
        ),
        migrations.RunPython(populate_contact_email, clear_migrated_contact_email),
        migrations.AddField(
            model_name='workshop',
            name='duracao_minutos',
            field=models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='workshop',
            name='inscricoes_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='local',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='workshop',
            name='modalidade',
            field=models.CharField(choices=[('onsite', 'Presencial'), ('online', 'On-line'), ('hybrid', 'Híbrido')], default='onsite', max_length=12),
        ),
        migrations.AddField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('cancelled', 'Cancelado'), ('completed', 'Concluído')], default='published', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='core_user_unique_nonempty_email'),
        ),
    ]
