-- PIEM Tusker Power 3.1 — schema PostgreSQL/Supabase completo
-- Fonte de verdade: modelos e migrações Django até core.0004_operational_command_31.
-- Execute somente em um projeto Supabase vazio. O bloco de proteção abaixo impede
-- sobrescrever uma instalação que já possua a tabela core_user.

BEGIN;

DO $piem_guard$
BEGIN
    IF to_regclass('public.core_user') IS NOT NULL THEN
        RAISE EXCEPTION 'PIEM: core_user já existe. Use as migrações Django; o instalador completo não sobrescreve dados.';
    END IF;
END
$piem_guard$;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- Controle de migrações e autenticação Django
-- ---------------------------------------------------------------------------

CREATE TABLE public.django_migrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    applied timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.django_content_type (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label varchar(100) NOT NULL,
    model varchar(100) NOT NULL,
    CONSTRAINT django_content_type_app_model_uniq UNIQUE (app_label, model)
);

CREATE TABLE public.auth_permission (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename varchar(100) NOT NULL,
    CONSTRAINT auth_permission_content_type_fk
        FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT auth_permission_content_codename_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE public.auth_group (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE
);

CREATE TABLE public.auth_group_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_group_fk
        FOREIGN KEY (group_id) REFERENCES public.auth_group(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT auth_group_permissions_permission_fk
        FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT auth_group_permissions_uniq UNIQUE (group_id, permission_id)
);

-- ---------------------------------------------------------------------------
-- Escolas, contas e vínculos de acesso
-- ---------------------------------------------------------------------------

CREATE TABLE public.core_school (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(180) NOT NULL,
    codigo varchar(40) NOT NULL UNIQUE,
    cidade varchar(100) NOT NULL DEFAULT '',
    estado varchar(2) NOT NULL DEFAULT '',
    ativa boolean NOT NULL DEFAULT true
);

CREATE TABLE public.core_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password varchar(128) NOT NULL,
    last_login timestamptz NULL,
    is_superuser boolean NOT NULL DEFAULT false,
    identifier varchar(150) NOT NULL UNIQUE,
    email varchar(254) NOT NULL DEFAULT '',
    nome varchar(150) NOT NULL,
    perfil_acesso varchar(16) NOT NULL DEFAULT 'student',
    area_interesse varchar(100) NOT NULL DEFAULT 'Tecnologia da Informação',
    escola_id bigint NULL,
    turma_id bigint NULL,
    biografia text NOT NULL DEFAULT '',
    competencias varchar(500) NOT NULL DEFAULT '',
    linkedin_url varchar(200) NOT NULL DEFAULT '',
    consentimento_vitrine boolean NOT NULL DEFAULT false,
    public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    is_active boolean NOT NULL DEFAULT true,
    is_staff boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT core_user_role_check
        CHECK (perfil_acesso IN ('student', 'teacher', 'admin', 'recruiter')),
    CONSTRAINT core_user_school_fk
        FOREIGN KEY (escola_id) REFERENCES public.core_school(id) ON DELETE SET NULL
        DEFERRABLE INITIALLY DEFERRED
);

CREATE UNIQUE INDEX core_user_unique_nonempty_email
    ON public.core_user (email) WHERE email <> '';

CREATE TABLE public.core_user_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT core_user_groups_user_fk
        FOREIGN KEY (user_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_user_groups_group_fk
        FOREIGN KEY (group_id) REFERENCES public.auth_group(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_user_groups_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE public.core_user_user_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT core_user_permissions_user_fk
        FOREIGN KEY (user_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_user_permissions_permission_fk
        FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_user_permissions_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE public.core_schoolclass (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    escola_id bigint NOT NULL,
    nome varchar(80) NOT NULL,
    ano_letivo integer NOT NULL DEFAULT 2026,
    serie smallint NOT NULL DEFAULT 3,
    CONSTRAINT core_schoolclass_school_fk
        FOREIGN KEY (escola_id) REFERENCES public.core_school(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_schoolclass_uniq UNIQUE (escola_id, nome, ano_letivo),
    CONSTRAINT core_schoolclass_year_check CHECK (ano_letivo >= 0),
    CONSTRAINT core_schoolclass_grade_check CHECK (serie BETWEEN 1 AND 3)
);

ALTER TABLE public.core_user
    ADD CONSTRAINT core_user_class_fk
    FOREIGN KEY (turma_id) REFERENCES public.core_schoolclass(id) ON DELETE SET NULL
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE public.core_schoolclass_professores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schoolclass_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT core_class_teachers_class_fk
        FOREIGN KEY (schoolclass_id) REFERENCES public.core_schoolclass(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_class_teachers_user_fk
        FOREIGN KEY (user_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_class_teachers_uniq UNIQUE (schoolclass_id, user_id)
);

CREATE TABLE public.django_admin_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_time timestamptz NOT NULL DEFAULT now(),
    object_id text NULL,
    object_repr varchar(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL DEFAULT '',
    content_type_id integer NULL,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_content_type_fk
        FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) ON DELETE SET NULL
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT django_admin_log_user_fk
        FOREIGN KEY (user_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT django_admin_log_action_flag_check CHECK (action_flag >= 0)
);

CREATE TABLE public.django_session (
    session_key varchar(40) PRIMARY KEY,
    session_data text NOT NULL,
    expire_date timestamptz NOT NULL
);

-- ---------------------------------------------------------------------------
-- Cursos, frequência, portfólio e certificação
-- ---------------------------------------------------------------------------

CREATE TABLE public.core_workshop (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo varchar(160) NOT NULL,
    area varchar(100) NOT NULL,
    data timestamptz NOT NULL,
    mentor_id bigint NULL,
    escola_id bigint NULL,
    descricao text NOT NULL,
    vagas integer NOT NULL DEFAULT 30,
    imagem_query varchar(120) NOT NULL DEFAULT '',
    status varchar(16) NOT NULL DEFAULT 'published',
    modalidade varchar(12) NOT NULL DEFAULT 'onsite',
    local varchar(180) NOT NULL DEFAULT '',
    duracao_minutos smallint NOT NULL DEFAULT 120,
    inscricoes_ate timestamptz NULL,
    CONSTRAINT core_workshop_mentor_fk
        FOREIGN KEY (mentor_id) REFERENCES public.core_user(id) ON DELETE SET NULL
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_workshop_school_fk
        FOREIGN KEY (escola_id) REFERENCES public.core_school(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_workshop_status_check
        CHECK (status IN ('draft', 'published', 'cancelled', 'completed')),
    CONSTRAINT core_workshop_modality_check
        CHECK (modalidade IN ('onsite', 'online', 'hybrid')),
    CONSTRAINT core_workshop_capacity_check CHECK (vagas > 0),
    CONSTRAINT core_workshop_duration_check CHECK (duracao_minutos BETWEEN 30 AND 600)
);

CREATE TABLE public.core_workshopenrollment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    workshop_id bigint NOT NULL,
    criado_em timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT core_enrollment_user_fk
        FOREIGN KEY (user_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_enrollment_workshop_fk
        FOREIGN KEY (workshop_id) REFERENCES public.core_workshop(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_enrollment_uniq UNIQUE (user_id, workshop_id)
);

CREATE TABLE public.core_attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    data date NOT NULL,
    presente boolean NOT NULL DEFAULT true,
    registrado_por_id bigint NULL,
    CONSTRAINT core_attendance_user_fk
        FOREIGN KEY (user_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_attendance_registrar_fk
        FOREIGN KEY (registrado_por_id) REFERENCES public.core_user(id) ON DELETE SET NULL
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_attendance_user_date_uniq UNIQUE (user_id, data)
);

CREATE TABLE public.core_studentproject (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id bigint NOT NULL,
    titulo varchar(160) NOT NULL,
    area varchar(100) NOT NULL,
    resumo text NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'ideia',
    publico boolean NOT NULL DEFAULT false,
    link_projeto varchar(200) NOT NULL DEFAULT '',
    link_github varchar(200) NOT NULL DEFAULT '',
    destaque boolean NOT NULL DEFAULT false,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT core_project_student_fk
        FOREIGN KEY (aluno_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_project_status_check
        CHECK (status IN ('ideia', 'desenvolvimento', 'concluido'))
);

CREATE TABLE public.core_certificate (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id bigint NOT NULL,
    projeto_id bigint NOT NULL UNIQUE,
    codigo uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    emitido_em timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT core_certificate_student_fk
        FOREIGN KEY (aluno_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_certificate_project_fk
        FOREIGN KEY (projeto_id) REFERENCES public.core_studentproject(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED
);

-- ---------------------------------------------------------------------------
-- Desafios, avaliações, vagas e mentorias
-- ---------------------------------------------------------------------------

CREATE TABLE public.core_practicalchallenge (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo varchar(180) NOT NULL,
    descricao text NOT NULL,
    area varchar(100) NOT NULL,
    pontos smallint NOT NULL DEFAULT 100,
    prazo timestamptz NULL,
    turma_id bigint NULL,
    criado_por_id bigint NOT NULL,
    ativo boolean NOT NULL DEFAULT true,
    criado_em timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT core_challenge_class_fk
        FOREIGN KEY (turma_id) REFERENCES public.core_schoolclass(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_challenge_creator_fk
        FOREIGN KEY (criado_por_id) REFERENCES public.core_user(id) ON DELETE RESTRICT
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_challenge_points_check CHECK (pontos BETWEEN 1 AND 350)
);

CREATE TABLE public.core_challengesubmission (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desafio_id bigint NOT NULL,
    aluno_id bigint NOT NULL,
    resposta text NOT NULL,
    anexo_url varchar(200) NOT NULL DEFAULT '',
    status varchar(16) NOT NULL DEFAULT 'pending',
    pontos_atribuidos smallint NOT NULL DEFAULT 0,
    feedback text NOT NULL DEFAULT '',
    avaliado_por_id bigint NULL,
    enviado_em timestamptz NOT NULL DEFAULT now(),
    avaliado_em timestamptz NULL,
    CONSTRAINT core_submission_challenge_fk
        FOREIGN KEY (desafio_id) REFERENCES public.core_practicalchallenge(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_submission_student_fk
        FOREIGN KEY (aluno_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_submission_reviewer_fk
        FOREIGN KEY (avaliado_por_id) REFERENCES public.core_user(id) ON DELETE SET NULL
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_submission_uniq UNIQUE (desafio_id, aluno_id),
    CONSTRAINT core_submission_status_check
        CHECK (status IN ('pending', 'revision', 'approved')),
    CONSTRAINT core_submission_points_check CHECK (pontos_atribuidos >= 0)
);

CREATE TABLE public.core_softskillassessment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id bigint NOT NULL,
    avaliador_id bigint NOT NULL,
    comunicacao smallint NOT NULL,
    proatividade smallint NOT NULL,
    trabalho_equipe smallint NOT NULL,
    feedback text NOT NULL DEFAULT '',
    criado_em timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT core_softskill_student_fk
        FOREIGN KEY (aluno_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_softskill_reviewer_fk
        FOREIGN KEY (avaliador_id) REFERENCES public.core_user(id) ON DELETE RESTRICT
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_softskill_communication_check CHECK (comunicacao BETWEEN 1 AND 5),
    CONSTRAINT core_softskill_initiative_check CHECK (proatividade BETWEEN 1 AND 5),
    CONSTRAINT core_softskill_teamwork_check CHECK (trabalho_equipe BETWEEN 1 AND 5)
);

CREATE TABLE public.core_jobopportunity (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo varchar(180) NOT NULL,
    empresa varchar(160) NOT NULL,
    descricao text NOT NULL,
    competencias varchar(500) NOT NULL DEFAULT '',
    modalidade varchar(20) NOT NULL DEFAULT 'Presencial',
    tipo varchar(16) NOT NULL DEFAULT 'apprentice',
    localidade varchar(140) NOT NULL DEFAULT '',
    publicada_por_id bigint NOT NULL,
    escola_id bigint NULL,
    ativa boolean NOT NULL DEFAULT true,
    criada_em timestamptz NOT NULL DEFAULT now(),
    encerra_em timestamptz NULL,
    CONSTRAINT core_job_publisher_fk
        FOREIGN KEY (publicada_por_id) REFERENCES public.core_user(id) ON DELETE RESTRICT
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_job_school_fk
        FOREIGN KEY (escola_id) REFERENCES public.core_school(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_job_type_check
        CHECK (tipo IN ('apprentice', 'internship', 'entry'))
);

CREATE TABLE public.core_jobapplication (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaga_id bigint NOT NULL,
    aluno_id bigint NOT NULL,
    etapa varchar(16) NOT NULL DEFAULT 'applied',
    carta_apresentacao text NOT NULL DEFAULT '',
    criada_em timestamptz NOT NULL DEFAULT now(),
    atualizada_em timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT core_application_job_fk
        FOREIGN KEY (vaga_id) REFERENCES public.core_jobopportunity(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_application_student_fk
        FOREIGN KEY (aluno_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_application_uniq UNIQUE (vaga_id, aluno_id),
    CONSTRAINT core_application_stage_check
        CHECK (etapa IN ('applied', 'screening', 'interview', 'offer', 'hired', 'rejected'))
);

CREATE TABLE public.core_mentorshipsession (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo varchar(180) NOT NULL,
    mentor_id bigint NOT NULL,
    aluno_id bigint NOT NULL,
    inicio timestamptz NOT NULL,
    duracao_minutos smallint NOT NULL DEFAULT 45,
    link_reuniao varchar(200) NOT NULL DEFAULT '',
    observacoes text NOT NULL DEFAULT '',
    confirmada boolean NOT NULL DEFAULT false,
    CONSTRAINT core_mentorship_mentor_fk
        FOREIGN KEY (mentor_id) REFERENCES public.core_user(id) ON DELETE RESTRICT
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_mentorship_student_fk
        FOREIGN KEY (aluno_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_mentorship_duration_check CHECK (duracao_minutos > 0)
);

-- ---------------------------------------------------------------------------
-- Tutor, Canal Seguro e auditoria
-- ---------------------------------------------------------------------------

CREATE TABLE public.core_chatsession (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    titulo varchar(120) NOT NULL DEFAULT 'Conversa com Tutor PIEM',
    criada_em timestamptz NOT NULL DEFAULT now(),
    atualizada_em timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT core_chatsession_user_fk
        FOREIGN KEY (user_id) REFERENCES public.core_user(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE public.core_chatmessage (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL,
    role varchar(12) NOT NULL,
    content text NOT NULL,
    provider varchar(24) NOT NULL DEFAULT '',
    criada_em timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT core_chatmessage_session_fk
        FOREIGN KEY (session_id) REFERENCES public.core_chatsession(id) ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_chatmessage_role_check CHECK (role IN ('user', 'assistant'))
);

CREATE TABLE public.core_safereport (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocolo uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    escola_id bigint NULL,
    categoria varchar(80) NOT NULL DEFAULT 'Acolhimento',
    mensagem text NOT NULL,
    contato_seguro text NOT NULL DEFAULT '',
    criado_em timestamptz NOT NULL DEFAULT now(),
    tratado boolean NOT NULL DEFAULT false,
    status varchar(16) NOT NULL DEFAULT 'open',
    CONSTRAINT core_safereport_school_fk
        FOREIGN KEY (escola_id) REFERENCES public.core_school(id) ON DELETE SET NULL
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT core_safereport_status_check
        CHECK (status IN ('open', 'in_progress', 'resolved'))
);

CREATE TABLE public.core_auditlog (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ator_id bigint NULL,
    acao varchar(80) NOT NULL,
    entidade varchar(80) NOT NULL,
    entidade_id varchar(64) NOT NULL DEFAULT '',
    detalhes jsonb NOT NULL DEFAULT '{}'::jsonb,
    ip inet NULL,
    criado_em timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT core_audit_actor_fk
        FOREIGN KEY (ator_id) REFERENCES public.core_user(id) ON DELETE SET NULL
        DEFERRABLE INITIALLY DEFERRED
);

-- ---------------------------------------------------------------------------
-- Índices operacionais e de chaves estrangeiras
-- ---------------------------------------------------------------------------

CREATE INDEX auth_permission_content_type_idx ON public.auth_permission(content_type_id);
CREATE INDEX auth_group_permissions_group_idx ON public.auth_group_permissions(group_id);
CREATE INDEX auth_group_permissions_permission_idx ON public.auth_group_permissions(permission_id);
CREATE INDEX core_user_school_idx ON public.core_user(escola_id);
CREATE INDEX core_user_class_idx ON public.core_user(turma_id);
CREATE INDEX core_user_school_role_idx ON public.core_user(escola_id, perfil_acesso);
CREATE INDEX core_user_groups_user_idx ON public.core_user_groups(user_id);
CREATE INDEX core_user_groups_group_idx ON public.core_user_groups(group_id);
CREATE INDEX core_user_permissions_user_idx ON public.core_user_user_permissions(user_id);
CREATE INDEX core_user_permissions_permission_idx ON public.core_user_user_permissions(permission_id);
CREATE INDEX core_schoolclass_school_idx ON public.core_schoolclass(escola_id);
CREATE INDEX core_class_teachers_class_idx ON public.core_schoolclass_professores(schoolclass_id);
CREATE INDEX core_class_teachers_user_idx ON public.core_schoolclass_professores(user_id);
CREATE INDEX django_admin_log_content_type_idx ON public.django_admin_log(content_type_id);
CREATE INDEX django_admin_log_user_idx ON public.django_admin_log(user_id);
CREATE INDEX django_session_expire_idx ON public.django_session(expire_date);
CREATE INDEX core_workshop_mentor_idx ON public.core_workshop(mentor_id);
CREATE INDEX core_workshop_school_idx ON public.core_workshop(escola_id);
CREATE INDEX core_workshop_catalog_idx ON public.core_workshop(status, data, area, modalidade);
CREATE INDEX core_enrollment_user_idx ON public.core_workshopenrollment(user_id);
CREATE INDEX core_enrollment_workshop_idx ON public.core_workshopenrollment(workshop_id);
CREATE INDEX core_attendance_user_idx ON public.core_attendance(user_id);
CREATE INDEX core_attendance_registrar_idx ON public.core_attendance(registrado_por_id);
CREATE INDEX core_project_student_idx ON public.core_studentproject(aluno_id);
CREATE INDEX core_certificate_student_idx ON public.core_certificate(aluno_id);
CREATE INDEX core_challenge_class_idx ON public.core_practicalchallenge(turma_id);
CREATE INDEX core_challenge_creator_idx ON public.core_practicalchallenge(criado_por_id);
CREATE INDEX core_submission_challenge_idx ON public.core_challengesubmission(desafio_id);
CREATE INDEX core_submission_student_idx ON public.core_challengesubmission(aluno_id);
CREATE INDEX core_submission_reviewer_idx ON public.core_challengesubmission(avaliado_por_id);
CREATE INDEX core_submission_status_idx ON public.core_challengesubmission(status, enviado_em DESC);
CREATE INDEX core_softskill_student_idx ON public.core_softskillassessment(aluno_id);
CREATE INDEX core_softskill_reviewer_idx ON public.core_softskillassessment(avaliador_id);
CREATE INDEX core_job_publisher_idx ON public.core_jobopportunity(publicada_por_id);
CREATE INDEX core_job_school_idx ON public.core_jobopportunity(escola_id);
CREATE INDEX core_job_school_active_idx ON public.core_jobopportunity(escola_id, ativa, criada_em DESC);
CREATE INDEX core_application_job_idx ON public.core_jobapplication(vaga_id);
CREATE INDEX core_application_student_idx ON public.core_jobapplication(aluno_id);
CREATE INDEX core_mentorship_mentor_idx ON public.core_mentorshipsession(mentor_id);
CREATE INDEX core_mentorship_student_idx ON public.core_mentorshipsession(aluno_id);
CREATE INDEX core_chatsession_user_idx ON public.core_chatsession(user_id);
CREATE INDEX core_chatmessage_session_idx ON public.core_chatmessage(session_id);
CREATE INDEX core_safereport_school_idx ON public.core_safereport(escola_id);
CREATE INDEX core_audit_actor_idx ON public.core_auditlog(ator_id);
CREATE INDEX core_audit_created_idx ON public.core_auditlog(criado_em DESC);

-- ---------------------------------------------------------------------------
-- Segurança Supabase: todo acesso escolar passa pelo backend Django.
-- Os papéis REST públicos não recebem acesso direto às tabelas do PIEM.
-- ---------------------------------------------------------------------------

DO $piem_security$
DECLARE
    table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'core_school', 'core_user', 'core_schoolclass', 'core_schoolclass_professores',
        'core_workshop', 'core_workshopenrollment', 'core_attendance', 'core_studentproject',
        'core_certificate', 'core_practicalchallenge', 'core_challengesubmission',
        'core_softskillassessment', 'core_jobopportunity', 'core_jobapplication',
        'core_mentorshipsession', 'core_chatsession', 'core_chatmessage', 'core_safereport',
        'core_auditlog'
    ] LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
    END LOOP;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        FOREACH table_name IN ARRAY ARRAY[
            'django_migrations', 'django_content_type', 'django_admin_log', 'django_session',
            'auth_permission', 'auth_group', 'auth_group_permissions',
            'core_user_groups', 'core_user_user_permissions', 'core_school', 'core_user',
            'core_schoolclass', 'core_schoolclass_professores', 'core_workshop',
            'core_workshopenrollment', 'core_attendance', 'core_studentproject',
            'core_certificate', 'core_practicalchallenge', 'core_challengesubmission',
            'core_softskillassessment', 'core_jobopportunity', 'core_jobapplication',
            'core_mentorshipsession', 'core_chatsession', 'core_chatmessage',
            'core_safereport', 'core_auditlog'
        ] LOOP
            EXECUTE format('REVOKE ALL PRIVILEGES ON TABLE public.%I FROM anon', table_name);
        END LOOP;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        FOREACH table_name IN ARRAY ARRAY[
            'django_migrations', 'django_content_type', 'django_admin_log', 'django_session',
            'auth_permission', 'auth_group', 'auth_group_permissions',
            'core_user_groups', 'core_user_user_permissions', 'core_school', 'core_user',
            'core_schoolclass', 'core_schoolclass_professores', 'core_workshop',
            'core_workshopenrollment', 'core_attendance', 'core_studentproject',
            'core_certificate', 'core_practicalchallenge', 'core_challengesubmission',
            'core_softskillassessment', 'core_jobopportunity', 'core_jobapplication',
            'core_mentorshipsession', 'core_chatsession', 'core_chatmessage',
            'core_safereport', 'core_auditlog'
        ] LOOP
            EXECUTE format('REVOKE ALL PRIVILEGES ON TABLE public.%I FROM authenticated', table_name);
        END LOOP;
    END IF;
END
$piem_security$;

COMMIT;
